---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-a91af927b18aace69cffeb257e3fff69
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/Ascendant-Systems/podinfo-deploy.git
